name: Publish Docker
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@0.1.1
        with:
          find: "##VERSION##"
          replace: "0.1.${{ github.run_number}}"
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: goddchen/hidden-numbers
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          dockerfile: docker/Dockerfile
